#funcion print ()
print("Este es un String","Hola Mundo!")
print("Este es un entero", 35)
print("Este es un float", 3.14)
print("Este es un booleano",True)
print(35)
print(3.14)
print(True)
# function type nos permite saber tipos de datos
print(type(True))
print(type(3.14))
print(type(3))
print(type("G"))